# @package _group_

ads: "/projets/samova/leocances/AudioSet/hdfs"
cifar10: "/projets/samova/elabbe/corpus/CIFAR10"
esc10: "/projets/samova/elabbe/corpus/ESC10"
fsd50k: null
gsc: "/projets/samova/elabbe/corpus/GSC"
pvc: "/projets/samova/leocances"
ubs8k: "/projets/samova/leocances/UrbanSound8K"
