name: env_sslh
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.2.0
  - audioread=2.1.8
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.2.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.0
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.2
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-MANIFEST.in=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - libllvm10=10.0.1
  - libogg=1.3.2
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - librosa=0.8.0
  - libsndfile=1.0.29
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.34.0
  - lz4-c=1.9.2
  - markdown=3.3.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - nettle=3.4.1
  - networkx=2.5
  - ninja=1.10.1
  - notebook=6.1.4
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pooch=1.2.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.7.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pysoundfile=0.10.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - resampy=0.2.2
  - rsa=4.6
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=50.3.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.1
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - x264=1!152.20180806
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.2
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - advertorch==0.2.3
    - dataclasses==0.6
    - future==0.18.2
    - nltk==3.5
    - regex==2020.11.13
    - git+https://github.com/leocances/pytorch_metrics
    - git+https://github.com/leocances/UrbanSound8K@new_data_management
    - git+https://github.com/leocances/augmentation_utils
    - git+https://github.com/Labbeti/MLU@dev
