# @package warmup

_target_: "sslh.callbacks.warmup.WarmUpCallback"

target_value: ${pl.lambda_u}
warmup_len: 16000
warmup_rule: "linear_increase"
on_epoch: false
target_attr: "lambda_u"
start_step: 0
