# @package _global_

defaults:
  - common
  - aug@aug_s: ident
  - aug@aug_u: ident
  - aug@val_aug: ident
  - data: ssl_esc10
  - model: wideresnet28
  - optim: adam
  - path: local
  - pl: deep_co_training
  - sched: softcosine
  - trainer: default
  - warmup: dct
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog
  - _self_

optim:
  lr: 5e-4
data:
  dm:
    bsize_s: 6
    bsize_u: 58
