# @package pl

defaults:
  - /criterion@criterion_s: ce_vec
  - /criterion@criterion_ccost: mse
  - /activation@activation: softmax
  - /activation@log_activation: log_softmax

_target_: "sslh.pl_modules.mean_teacher.mean_teacher_cc_mode.MeanTeacherCCMode"

log_on_epoch: ${data.log_on_epoch}
decay: 0.999
lambda_ccost: 1.0
buffers_mode: "none"
ccost_out_mode: "probs"
