# @package pl

defaults:
  - /criterion@criterion_s: ce_vec
  - /criterion@criterion_ccost: mse
  - /activation@activation: softmax

_target_: "sslh.pl_modules.mean_teacher.mean_teacher.MeanTeacher"

log_on_epoch: ${data.log_on_epoch}
decay: 0.999
lambda_ccost: 1.0
buffers_mode: "none"
