# @package _group_

name: "FixMatchThresholdGuess"
acronym: "fmtg"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "none"
augm_weak: "weak"
augm_strong: "strong"
lambda_u: 1.0
threshold: 0.75
threshold_guess: 0.75
