# @package _group_

name: "MixMatchMultiSharp"
acronym: "mmm"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "mean"
augm_weak: "weak"
lambda_u: 1.0
n_augms: 2

alpha: 0.75
sharpen_threshold: 0.75
