# @package _group_

name: "MixMatchNoMixUp"
acronym: "mmn"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "mean"
augm_weak: "weak"
lambda_u: 1.0
n_augms: 2

temperature: 0.5
