# @package _group_

name: "PseudoLabeling"
acronym: "pl"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "none"
lambda_u: 1.0
threshold: 0.95

warmup:
  n_steps: null
  ratio_n_steps: 0.5
  on_epoch: false
