# @package _group_

name: "ReMixMatchNoMixUp"
acronym: "rmmn"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
criterion_u1: "CrossEntropy"
reduction: "mean"
augm_weak: "weak"
augm_strong: "strong"
history: 128
lambda_u: 1.5
lambda_u1: 0.5
n_augms: 2
temperature: 0.5

criterion_r: "CrossEntropy"
lambda_r: 0.5
activation_r: "softmax"
