# @package _group_

verbose: true
debug: false
datetime: "${now:%Y-%m-%d_%H:%M:%S}"
seed: 1234
tag: ""
epochs: 1
max_steps: null
cpus: 12
gpus: 1
logdir: "../boards"
resume_path: null

logger:
  save_dir: "${logdir}/${data.acronym}"
  name: "${expt.name}"
  version: "${datetime}${tag}"
  default_hp_metric: true
  log_graph: false

checkpoint:
  monitor: "${data.monitor}"
  mode: "${data.monitor_mode}"
  save_last: true
  save_top_k: 1
  verbose: ${verbose}

trainer:
  accelerator: null
  max_epochs: ${epochs}
  gpus: ${gpus}
  max_steps: null
  resume_from_checkpoint: ${resume_path}
  val_check_interval: ${data.val_check_interval}
  move_metrics_to_cpu: true
  deterministic: true
  terminate_on_nan: true
  multiple_trainloader_mode: "max_size_cycle"

hydra:
  # Set args save in board dir
  output_subdir: "${logger.save_dir}/${logger.name}/${logger.version}/hydra"
  # Set hydra working dir
  run:
    dir: "./"
