# @package _global_

defaults:
  - common
  - hydra/job_logging: custom
  - data: esc10
  - model: wideresnet28
  - optim: adam
  - path: default
  - sched: softcosine
  - expt: deep_co_training
  - warmup: none

bsize_s: 10
bsize_u: 90
ratio_s: 0.1
ratio_u: 0.9
