# @package _global_

defaults:
  - common
  - hydra/job_logging: custom  # redirect log file to output_subdir
  - dataset: esc10
  - model: wideresnet28
  - optim: adam
  - path: default
  - sched: softcosine
  - expt: mixup

bsize: 60
ratio: 1.0
