# @package _global_
defaults:
  - dataset: esc10
  - model: wrn28
  - experiment: mixup
  - optim: adam
  - path: default
  - sched: cosine

datetime: "${now:%Y-%m-%d_%H:%M:%S}"
tag: ""
epochs: 10
max_it: null
cpus: 12
gpus: 1
logdir: "../boards"
seed: 1234
bsize: 60
ratio: 1.0


hydra:
  # Disable log file
  job_logging: null
  # Set args save in board dir
  output_subdir: ${logdir}/${dataset.name}/${experiment.fullname}/${datetime}${tag}/.hydra
  # Set hydra working dir
  run:
    dir: ./
