# @package _global_
defaults:
  - dataset: esc10
  - model: wrn28rot
  - experiment: remixmatch
  - optim: adam
  - path: default
  - sched: cosine

verbose: false
datetime: "${now:%Y-%m-%d_%H:%M:%S}"
seed: 1234
tag: ""
epochs: 10
max_it: null
cpus: 12
gpus: 1
logdir: ${path.logdir}
resume_path: null
bsize_s: 30
bsize_u: 30
ratio_s: 0.1
ratio_u: 0.9

hydra:
  # Disable log file
  job_logging: null
  # Set args save in board dir
  output_subdir: ${logdir}/${dataset.name}/${experiment.fullname}/${datetime}${tag}/.hydra
  # Set hydra working dir
  run:
    dir: ./
