# @package _group_

name: "ADS"
fullname: "AudioSet"
num_classes: 527
root: ${path.ads}
monitor: "val/fscore"
monitor_mode: "max"
val_check_interval: 10000
log_on_epoch: false
sample_rate: 32000

train_subset: "unbalanced"
nb_train_steps: 125000
