# @package _group_

name: "CIFAR10"
acronym: "CIFAR10"

n_classes: 10
root: ${path.cifar10}
monitor: "val/acc"
monitor_mode: "max"
val_check_interval: 1.0
log_on_epoch: true

download: true

transform:
  mean: [0.4914009, 0.48215896, 0.4465308]
  std: [0.24703279, 0.24348423, 0.26158753]
