# @package _group_

name: "GoogleSpeechCommands"
acronym: "GSC"

n_classes: 35
root: ${path.gsc}
monitor: "val/acc"
monitor_mode: "max"
val_check_interval: 1.0
log_on_epoch: true
sample_rate: 16000

download: true

transform:
  n_mels: 64
  hop_length: 512
  n_fft: 2048