# @package _group_

name: "PVC"
fullname: "Primate_Vocalisations_Corpus"
num_classes: 5
root: ${path.pvc}
monitor: "val/acc"
monitor_mode: "max"
val_check_interval: 1000
log_on_epoch: false
sample_rate: 16000

nb_train_steps: 50000
