# @package _group_

name: "UBS8K"
fullname: "UrbanSound8k"
num_classes: 10
root: ${path.ubs8k}
monitor: "val/acc"
monitor_mode: "max"
val_check_interval: 1.0
log_on_epoch: true

folds_train: [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
folds_val: [ 10 ]
