# @package _group_

name: "UrbanSound8k"
acronym: "UBS8K"

n_classes: 10
root: ${path.ubs8k}
monitor: "val/acc"
monitor_mode: "max"
val_check_interval: 1.0
log_on_epoch: true
sample_rate: 22050

# If null, the program detect automatically the remaining folds
folds_train: null
folds_val: [ 10 ]

transform:
  n_mels: 64
  hop_length: 512
  n_fft: 2048
