# @package aug

- type: "waveform"
  aug:
    _target_: "sslh.transforms.waveform.occlusion.Occlusion"
    scales: [0.0, 0.25]
    p: 0.5
- type: "waveform"
  aug:
    _target_: "sslh.transforms.waveform.resample_pad_crop.ResamplePadCrop"
    rates: [0.5, 1.5]
    align: "random"
    p: 0.5
- type: "spectrogram"
  aug:
    _target_: "sslh.transforms.spectrogram.cutoutspec.CutOutSpec"
    freq_scales: [0.1, 0.5]
    time_scales: [0.1, 0.5]
    fill_value: -80.0
    p: 0.5
