# @package pl

_target_: "sslh.pl_modules.deep_co_training.deep_co_training.DeepCoTraining"

activation: "softmax"
log_activation: log_${pl.activation}
criterion_s: "CrossEntropy"
reduction: "mean"
epsilon: 0.02
lambda_cot: 1.0
lambda_diff: 0.5
duplicate_loader_s: true
