# @package pl

_target_: "sslh.pl_modules.fixmatch.fixmix.FixMix"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "none"
lambda_u: 1.0
threshold: 0.95
alpha: 0.75
