# @package pl

defaults:
  - /criterion@criterion_s: ce
  - /criterion@criterion_ccost: mse
  - /activation@activation: softmax
  - /trans@noise: gaussian_noise

_target_: "sslh.pl_modules.mean_teacher.mean_teacher_aug.MeanTeacherAug"

decay: 0.999
lambda_ccost: 1.0
