# @package pl

defaults:
  - /criterion@criterion_s: ce
  - /criterion@criterion_ccost: mse
  - /activation@log_activation: log_softmax
  - /trans@noise: gaussian_noise

_target_: "sslh.pl_modules.mean_teacher.mean_teacher_cc_mode.MeanTeacherCCMode"

decay: 0.999
lambda_ccost: 1.0
ccost_out_mode: "probs"
