# @package pl

_target_: "sslh.pl_modules.mixmatch.mixmatch_nomixup.MixMatchNoMixUp"

activation: "softmax"
criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
reduction: "mean"
lambda_u: 1.0
n_augms: 2

temperature: 0.5
