# @package pl

_target_: "sslh.pl_modules.remixmatch.remixmatch.ReMixMatch"

activation: "softmax"
reduction: "mean"

criterion_s: "CrossEntropy"
criterion_u: "CrossEntropy"
criterion_u1: "CrossEntropy"
history: 128
lambda_u: 1.5
lambda_u1: 0.5
n_augms: 2
temperature: 0.5

alpha: 0.75
criterion_r: "CrossEntropy"
lambda_r: 0.5
activation_r: "softmax"
self_transform_mode: "hvflips"
