# @package aug

- type: "spectrogram"
  aug:
    _target_: "sslh.transforms.spectrogram.spec_aug.SpecAugmentation"
    freq_drop_width: 8
    freq_stripes_num: 2
    time_drop_width: 16
    time_stripes_num: 2
    time_dim: 3
    freq_dim: 2
    inplace: true
    p: 1.0

- type: "waveform"
  aug:
    _target_: "sslh.transforms.waveform.speed_perturbation.SpeedPerturbation"
    rates: [0.25, 1.75]
    align: "random"
    p: 1.0
